# Generated by Django 4.1.4 on 2022-12-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('table_num', models.IntegerField()),
                ('email', models.CharField(max_length=90)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('num_seats', models.IntegerField()),
                ('shape', models.BooleanField()),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('width', models.DecimalField(decimal_places=2, max_digits=3)),
                ('high', models.DecimalField(decimal_places=2, max_digits=3)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
