# Generated by Django 4.1.4 on 2022-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_table_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
